name: "\U0001F41E Bug report"
description: Report an issue with Zameel
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: bug-type
    attributes:
      label: What type of issue are you facing?
      options:
        - Functionality
        - Performance
        - User Experience
        - User Interface
        - Other

  - type: input
    id: other
    attributes:
      label: Other Bug Type
      placeholder: e.g. Compatibility
      description: "If you choose \"Other\" pleaser write the type, this is extremely helpful, if an other type has been submitted several times, it will be added to the types list."

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: "How the issue is triggered?"
      placeholder: e.g. Submitting new post form
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        1. Click on ...
        2. Check log

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens. A screenshots attachment would be great.
    validations:
      required: true

  - type: textarea
    id: other-info
    attributes:
      label: Additional information
      description: Add any other context about the problem here.

  - type: markdown
    attributes:
      value: |
        Please make sure that this issue hasn't been [reported before](https://github.com/khateeboveskey/zameel/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).